name: rtsp_viewer
description: A Flutter app for viewing RTSP video streams
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_android_video: ^1.3.8
  media_kit_libs_windows_video: ^1.0.9
  media_kit_libs_ios_video: ^1.1.4
  permission_handler: ^11.0.1
  image_picker: ^1.0.7

dependency_overrides:
  win32: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
